#!/usr/bin/env bash

# Usage:
# ./build_icons icon.png

# Windows
convert -background transparent "${1}" -define icon:auto-resize=16,32,48,64,256 $(basename $1 .png).ico

# macOS
convert -resize 16x16 "$1" "${2}"/icon_16x16.png
convert -resize 32x32 "$1" "${2}"/icon_16x16@2x.png
convert -resize 32x32 "$1" "${2}"/icon_32x32.png
convert -resize 64x64 "$1" "${2}"/icon_32x32@2x.png
convert -resize 128x128 "$1" "${2}"/icon_128x128.png
convert -resize 256x256 "$1" "${2}"/icon_128x128@2x.png
convert -resize 256x256 "$1" "${2}"/icon_256x256.png
convert -resize 512x512 "$1" "${2}"/icon_256x256@2x.png
convert -resize 512x512 "$1" "${2}"/icon_512x512.png
convert -resize 1024x1024 "$1" "${2}"/icon_512x512@2x.png
iconutil -c icns $(basename $1 .png).iconset